### ISSUE TITLE
Statement - I absolutely love your mod.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [coderbot16/ProjectY#8]
So its been a while since I have seen a cool cosmetic mod. I hope you keep adding your cool ideas to the world :D I promise to report anything that does not work as intended.

**Comment by coderbot16** [comment]
Thanks, I really appreciate it! While this mod is not my original idea, and draws heavily from XyCraft and HexCraft, it is definitely one of the nicer looking mods I’ve made. For the next update I currently am planning to implement the functional blocks when I get some more time, so that’s something to look forward to. Hope you have fun with the mod!

**Comment by P3rf3ctXZer0** [comment]
I do have a small piece of advice. Allow your mod to be module. If anything in the mod scene has taught me anything is none module mods often die due to mods that are have more features and are configurable.

**Comment by coderbot16** [comment]
I'm not entirely clear what modular would mean in the current state of the mod. One issue is how granular the modules should be, going from individual blocks to a few groups of many blocks. The current plan is to divide up the blocks into 3 categories - world, decoration, functional - and then allow disabling of each block type within each category. The only issue is it doesn't seem possible to disable JSON recipes through code, so that would clutter the log.

EDIT: Looks like http://www.minecraftforge.net/forum/topic/59872-112-disabling-recipes-in-configuration/ might be of interest, seems like a possibility.

**Comment by P3rf3ctXZer0** [comment]
So basically you could keep function and cosmetic in separate toggle categories. Since I grabbed the mod for cosmetic as I have plenty of functional mods. As I said your block textures are unique. One thing I would say you could do that no other mod is doing is allow canvas blocks.

I have not seen a mod that allows users to add custom filename.png to a the block pool. I have always wanted a mod like that but it does not exist. By allowing players to add a blockface of a custom design you basically add a way for users to dramatically add cosmetic styles. Not to mention since no one else has done something like this you would draw people to your mod.

**Comment by coderbot16** [comment]
The first part - separating functional and deforative blocks - is definitely possible.

The second part, though, seems to be something like ContentTweaker, where it allows you to add custom blocks within CraftTweaker. Everything aside from the glowing is handled by the vanilla format, so it’s possible to add additional blocks in that way.

**Comment by P3rf3ctXZer0** [comment]
No not a custom block but rather a block that adapts 128 x 128 pixel pngs as blocks. Content Tweaker only lets you use pre-existing materials.

**Comment by coderbot16** [comment]
I'm not sure what "adapting an image to a block" is supposed to mean. Here are my potential interpretations of it:

1. Creating a new block/item with ContentTweaker and then applying the image as a texture
2. Replacing the existing textures of a block/item through a resource pack
3. A custom block that allows you to select an arbitrary image for its appearance through a GUI

#1 and #2 are already provided by features outside of the mod, so therefore are out of scope. #3 is a relatively complex feature that while neat, also seems out of scope in relation to the other features of the mod.

**Comment by P3rf3ctXZer0** [comment]
.3 please

**Comment by coderbot16** [comment]
https://minecraft.curseforge.com/projects/onlinepictureframe or https://minecraft.curseforge.com/projects/signpicture would appear to do what #3 would be, they both appear to be pretty neat mods.

**Comment by coderbot16** [comment]
I assume that the provided mods were satisfactory for the purposes of having custom in game images, so I’ll just close this issue. Feel free to open another issue if you have any questions or concerns!
